FROM mcr.microsoft.com/dotnet/runtime:8.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY ["src/SenLink.Worker/SenLink.Worker.csproj", "src/SenLink.Worker/"]
COPY ["src/SenLink.Service/SenLink.Service.csproj", "src/SenLink.Service/"]
COPY ["src/SenLink.Domain/SenLink.Domain.csproj", "src/SenLink.Domain/"]
COPY ["src/SenLink.Shared/SenLink.Shared.csproj", "src/SenLink.Shared/"]
RUN dotnet restore "src/SenLink.Worker/SenLink.Worker.csproj"

COPY src/ .
WORKDIR "/src/SenLink.Worker"
RUN dotnet build "SenLink.Worker.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "SenLink.Worker.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "SenLink.Worker.dll"]